<a href="https://colab.research.google.com/github/ThitipongKan/DPDM65/blob/main/pre_procressing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import เพื่อดึง package data ตั้งชื่อเป็น pd
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive #เชื่อม google drive
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive

In [7]:
project_df = pd.read_csv('/content/drive/MyDrive/DPDM65/Copy of opendata_project.csv')
project_df.head()

,row_number,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,price_min,developer_id,developer_name_en,...,facility_meeting,facility_park,facility_playground,facility_pool,facility_security,date_created,date_finish,date_updated,source,url_project
0,7880.0,5ee08d64dda791001299b2a6,Winning Residence Sukhumvit Praksa,วินนิ่ง เรสซิเดนท์ สุขุมวิท แพรกษา,1,Detached House,บ้าน,3790000.0,developer_10678,"Winning Asset Plus Co., Ltd.",...,NaN,NaN,NaN,1.0,1.0,2020-06-10 14:36:04,NaN,2020-12-04 10:32:58,baania,https://baania.com/th/project/วินนิ่ง-เรสซิเดน...
1,16689.0,project_11326,Gift Condominium,กิ๊ฟท์ คอนโดมิเนียม,2,Condo,คอนโด,1100000.0,developer_7319,"Gift Asset Land Co.,Ltd.",...,NaN,1.0,NaN,1.0,1.0,2017-10-30 15:38:48,2013-01-01 07:00:00,2020-12-04 10:49:00,baania,https://baania.com/th/project/กิ๊ฟท์-คอนโดมิเน...
2,290.0,62739c4089233e001362b001,Sanrak 9 Sukprayoon Nong Krathum,แสนรัก 9 ศุขประยูร หนองกระทุ่ม,3,Townhome,ทาวน์โฮม,0.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,NaN,2022-05-05 16:43:28,NaN,2022-05-05 17:30:03,baania,https://baania.com/th/project/แสนรัก-9-ศุขประย...
3,20719.0,project_2010,Baan Sansabai 1,บ้านแสนสบาย 1,1,Detached House,บ้าน,0.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,NaN,2016-09-05 15:32:15,1970-01-02 07:00:00,2020-12-04 10:45:31,baania,https://baania.com/th/project/บ้านแสนสบาย-1-pr...
4,199.0,project_16838,Baanpruksa Ratchapruek-345,บ้านพฤกษา ราชพฤกษ์-345,3,Townhome,ทาวน์โฮม,1930000.0,developer_1026,"Preuksa Real Estate Co.,Ltd.",...,NaN,1.0,NaN,1.0,1.0,2019-09-05 11:49:37,1970-01-02 07:00:00,2021-03-17 12:00:04,baania,https://baania.com/th/project/บ้านพฤกษา-ราชพฤก...

In [5]:
unit_df = pd.read_csv('/content/drive/MyDrive/DPDM65/Copy of opendata_unittype.csv')

In [6]:
unit_df.head()

,row_number,unittype_id,project_id,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,area_total_min_wa,area_usable_min,price_min,...,count_room_guest,count_room_kitchen,count_room_living,count_room_maid,count_room_storage,count_room_utility,date_created,date_updated,source,url_unittype
0,27501,unittype_9565,project_2446,2 Bedroom,2,Condo,คอนโด,NaN,37.3,2500000.0,...,1.0,1.0,NaN,NaN,NaN,NaN,2021-11-19 18:00:09,2021-11-19 17:44:45,baania,https://baania.com/th/project/เฟ-ลิค-คอนโด-ลาด...
1,28777,unittype_10267,project_3543,บ้านแฝดสองชั้น Z-2,20000,Twin house,บ้านแฝด,40.0,150.0,2390000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-27 14:30:04,2022-01-27 14:22:55,baania,https://baania.com/th/project/เซน-บาย-ศิวาลัย-...
2,28865,unittype_471,project_143,1 Bedroom Type B,2,Condo,คอนโด,NaN,28.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-14 15:00:10,2022-01-14 14:40:04,baania,https://baania.com/th/project/วันพลัส-นายน์ทีน...
3,24988,unittype_19506,project_7766,Studio Floor 1-2,2,Condo,คอนโด,NaN,27.0,170000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-04 10:40:59,2020-10-14 01:06:48,baania,https://baania.com/th/project/บ้านสวนชมน้ำ-776...
4,38596,unittype_10290,project_3551,TH 3,3,Townhome,ทาวน์โฮม,NaN,182.0,2390000.0,...,1.0,1.0,NaN,NaN,2.0,NaN,2021-11-12 13:30:08,2021-02-03 12:12:54,baania,https://baania.com/th/project/เบล็สทาวน์-ศรีนค...

# DATA CLEANING

## Dealing with missing data

check missing data

In [8]:
project_df.describe()

,row_number,latitude,longitude,subdistrict_id,district_id,province_id,zipcode,count_unit,count_unittype,facility_clubhouse,facility_fitness,facility_meeting,facility_park,facility_playground,facility_pool,facility_security
count,23429.000000,23434.000000,23429.000000,23415.000000,23424.000000,23425.000000,23403.000000,21547.000000,18603.000000,6820.000000,8895.000000,2890.000000,11675.000000,6277.000000,9718.000000,16123.000000
mean,11715.000000,16.399159,100.600086,4216.201751,4001.917435,3942.592231,28209.221211,199.043765,2.325861,0.724340,0.848679,0.224913,0.894304,0.697308,0.874048,0.959809
std,6763.514064,176.896370,0.947247,2476.968321,1662.485878,1663.662562,24724.177495,320.029641,2.138378,0.446879,0.358382,0.417598,0.307461,0.459460,0.331812,0.196413
min,1.000000,6.839354,97.985808,1007.000000,1006.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5858.000000,13.347151,100.400282,3414.000000,3411.000000,3372.000000,10400.000000,49.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000
50%,11715.000000,13.753725,100.601281,3802.000000,3800.000000,3781.000000,20000.000000,108.000000,2.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000
75%,17572.000000,13.946742,100.912703,4527.000000,4000.000000,3781.000000,40000.000000,240.000000,3.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000
max,23429.000000,12160.000000,105.222114,20688.000000,20003.000000,10508.000000,390000.000000,10074.000000,96.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
project_df.isnull()

,row_number,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,price_min,developer_id,developer_name_en,...,facility_meeting,facility_park,facility_playground,facility_pool,facility_security,date_created,date_finish,date_updated,source,url_project
0,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,False,True,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,True,...,True,True,True,True,True,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,True,...,True,True,True,True,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,True,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23429,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False
23430,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,False,False,False,False,False,False
23431,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False
23432,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
23433,False,False,False,False,False,False,False,False,False,True,...,True,True,True,True,True,False,False,False,False,False

In [10]:
project_df.isnull().any() # .any() เอาค่าความจริงใน column มา or กัน

row_number                 True
project_id                False
name_en                   False
name_th                   False
propertytype_id           False
propertytype_name_en      False
propertytype_name_th      False
price_min                  True
developer_id              False
developer_name_en          True
developer_name_th          True
latitude                  False
longitude                  True
neighborhood_id            True
neighborhood_name_en       True
neighborhood_name_th       True
subdistrict_id             True
subdistrict_name_en        True
subdistrict_name_th        True
district_id                True
district_name_en           True
district_name_th           True
province_id                True
province_name_en           True
province_name_th           True
zipcode                    True
count_elevator             True
count_elevator_service     True
count_floor                True
count_parking              True
count_tower                True
count_unit                 True
count_unittype             True
facility_clubhouse         True
facility_fitness           True
facility_meeting           True
facility_park              True
facility_playground        True
facility_pool              True
facility_security          True
date_created               True
date_finish                True
date_updated               True
source                     True
url_project                True
dtype: bool

In [11]:
project_df.isnull().any().any()

True

In [12]:
project_df.isnull().all() # .all() เอาค่าความจริงใน column มา and กัน

row_number                False
project_id                False
name_en                   False
name_th                   False
propertytype_id           False
propertytype_name_en      False
propertytype_name_th      False
price_min                 False
developer_id              False
developer_name_en         False
developer_name_th         False
latitude                  False
longitude                 False
neighborhood_id           False
neighborhood_name_en      False
neighborhood_name_th      False
subdistrict_id            False
subdistrict_name_en       False
subdistrict_name_th       False
district_id               False
district_name_en          False
district_name_th          False
province_id               False
province_name_en          False
province_name_th          False
zipcode                   False
count_elevator            False
count_elevator_service    False
count_floor               False
count_parking             False
count_tower               False
count_unit                False
count_unittype            False
facility_clubhouse        False
facility_fitness          False
facility_meeting          False
facility_park             False
facility_playground       False
facility_pool             False
facility_security         False
date_created              False
date_finish               False
date_updated              False
source                    False
url_project               False
dtype: bool

### delete records with missing data (dropna())

null, Nan (Not a number), Na (Not authorised/Not available)== missing

In [14]:
project_df.shape

(23434, 45)

In [15]:
unit_df.shape

(42625, 27)

In [16]:
project_df.dropna()

Empty DataFrame
Columns: [row_number, project_id, name_en, name_th, propertytype_id, propertytype_name_en, propertytype_name_th, price_min, developer_id, developer_name_en, developer_name_th, latitude, longitude, neighborhood_id, neighborhood_name_en, neighborhood_name_th, subdistrict_id, subdistrict_name_en, subdistrict_name_th, district_id, district_name_en, district_name_th, province_id, province_name_en, province_name_th, zipcode, count_elevator, count_elevator_service, count_floor, count_parking, count_tower, count_unit, count_unittype, facility_clubhouse, facility_fitness, facility_meeting, facility_park, facility_playground, facility_pool, facility_security, date_created, date_finish, date_updated, source, url_project]
Index: []

[0 rows x 45 columns]

In [18]:
unit_df.dropna()

Empty DataFrame
Columns: [row_number, unittype_id, project_id, name_th, propertytype_id, propertytype_name_en, propertytype_name_th, area_total_min_wa, area_usable_min, price_min, count_airconditioner, count_elevator, count_floor_internal, count_parking, count_room_bath, count_room_bed, count_room_dinning, count_room_guest, count_room_kitchen, count_room_living, count_room_maid, count_room_storage, count_room_utility, date_created, date_updated, source, url_unittype]
Index: []

[0 rows x 27 columns]

In [19]:
project_df.dropna(axis = 1)

,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,developer_id,latitude
0,5ee08d64dda791001299b2a6,Winning Residence Sukhumvit Praksa,วินนิ่ง เรสซิเดนท์ สุขุมวิท แพรกษา,1,Detached House,บ้าน,developer_10678,13.570530
1,project_11326,Gift Condominium,กิ๊ฟท์ คอนโดมิเนียม,2,Condo,คอนโด,developer_7319,13.033814
2,62739c4089233e001362b001,Sanrak 9 Sukprayoon Nong Krathum,แสนรัก 9 ศุขประยูร หนองกระทุ่ม,3,Townhome,ทาวน์โฮม,developer_10510,13.417402
3,project_2010,Baan Sansabai 1,บ้านแสนสบาย 1,1,Detached House,บ้าน,developer_10510,15.038042
4,project_16838,Baanpruksa Ratchapruek-345,บ้านพฤกษา ราชพฤกษ์-345,3,Townhome,ทาวน์โฮม,developer_1026,13.965246
...,...,...,...,...,...,...,...,...
23429,project_12317,Baan Klangmeung Urbanion Ladphrao-Chokchai 4,บ้านกลางเมือง เออร์บาเนี่ยน ลาดพร้าว-โชคชัย 4,3,Townhome,ทาวน์โฮม,developer_1760,13.814468
23430,project_12057,@Home Kaset-Nawamin,แอทโฮม เกษตร-นวมินทร์,3,Townhome,ทาวน์โฮม,developer_1793,13.834361
23431,project_4461,I-Design Wongwaen-Ramintra,ไอ-ดีไซน์ วงแหวน-รามอินทรา,4,Commercial,อาคารพาณิชย์,developer_2217,13.859872
23432,project_144,Koolpunt Ville 15 Park Avenue,กุลพันธ์วิลล์ 15 พาร์ค อเวนิว,1,Detached House,บ้าน,developer_1004,18.808447
23433,project_16300,Thawisuk Garden Home,ทวีสุข การ์เด้นโฮม,1,Detached House,บ้าน,developer_10510,12.684945

In [21]:
project_df.dropna(axis = 1).isnull()

,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,developer_id,latitude
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
23429,False,False,False,False,False,False,False,False
23430,False,False,False,False,False,False,False,False
23431,False,False,False,False,False,False,False,False
23432,False,False,False,False,False,False,False,False
23433,False,False,False,False,False,False,False,False

In [22]:
project_df.dropna(axis = 1).isnull().any()

project_id              False
name_en                 False
name_th                 False
propertytype_id         False
propertytype_name_en    False
propertytype_name_th    False
developer_id            False
latitude                False
dtype: bool

In [24]:
print(project_df.isnull().any().any())
print(project_df.shape)

True
(23434, 45)

In [25]:
project_df2 = project_df.dropna(axis = 1)
project_df2.head()

,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,developer_id,latitude
0,5ee08d64dda791001299b2a6,Winning Residence Sukhumvit Praksa,วินนิ่ง เรสซิเดนท์ สุขุมวิท แพรกษา,1,Detached House,บ้าน,developer_10678,13.570530
1,project_11326,Gift Condominium,กิ๊ฟท์ คอนโดมิเนียม,2,Condo,คอนโด,developer_7319,13.033814
2,62739c4089233e001362b001,Sanrak 9 Sukprayoon Nong Krathum,แสนรัก 9 ศุขประยูร หนองกระทุ่ม,3,Townhome,ทาวน์โฮม,developer_10510,13.417402
3,project_2010,Baan Sansabai 1,บ้านแสนสบาย 1,1,Detached House,บ้าน,developer_10510,15.038042
4,project_16838,Baanpruksa Ratchapruek-345,บ้านพฤกษา ราชพฤกษ์-345,3,Townhome,ทาวน์โฮม,developer_1026,13.965246

In [20]:
unit_df.dropna(axis = 1)

,row_number,unittype_id,project_id,propertytype_id,propertytype_name_en,propertytype_name_th,date_created,date_updated,source
0,27501,unittype_9565,project_2446,2,Condo,คอนโด,2021-11-19 18:00:09,2021-11-19 17:44:45,baania
1,28777,unittype_10267,project_3543,20000,Twin house,บ้านแฝด,2022-01-27 14:30:04,2022-01-27 14:22:55,baania
2,28865,unittype_471,project_143,2,Condo,คอนโด,2022-01-14 15:00:10,2022-01-14 14:40:04,baania
3,24988,unittype_19506,project_7766,2,Condo,คอนโด,2020-12-04 10:40:59,2020-10-14 01:06:48,baania
4,38596,unittype_10290,project_3551,3,Townhome,ทาวน์โฮม,2021-11-12 13:30:08,2021-02-03 12:12:54,baania
...,...,...,...,...,...,...,...,...,...
42620,37109,unittype_38508,project_16864,1,Detached House,บ้าน,2021-11-12 13:22:37,2020-10-14 10:05:42,baania
42621,14,unittype_14016,project_5275,1,Detached House,บ้าน,2020-12-04 10:36:32,2020-10-14 00:37:51,baania
42622,41009,617bde1687dd2300149d2195,617bdd47f62011001350de07,3,Townhome,ทาวน์โฮม,2021-11-12 13:34:17,2021-10-29 18:43:09,baania
42623,9333,unittype_37375,project_16389,1,Detached House,บ้าน,2020-12-04 10:42:26,2020-10-14 19:30:46,baania
42624,780,unittype_17011,project_6762,1,Detached House,บ้าน,2021-11-12 13:19:43,2020-10-14 00:41:39,baania

In [26]:
project_df.head().iloc[:5,-7:]

,facility_pool,facility_security,date_created,date_finish,date_updated,source,url_project
0,1.0,1.0,2020-06-10 14:36:04,NaN,2020-12-04 10:32:58,baania,https://baania.com/th/project/วินนิ่ง-เรสซิเดน...
1,1.0,1.0,2017-10-30 15:38:48,2013-01-01 07:00:00,2020-12-04 10:49:00,baania,https://baania.com/th/project/กิ๊ฟท์-คอนโดมิเน...
2,NaN,NaN,2022-05-05 16:43:28,NaN,2022-05-05 17:30:03,baania,https://baania.com/th/project/แสนรัก-9-ศุขประย...
3,NaN,NaN,2016-09-05 15:32:15,1970-01-02 07:00:00,2020-12-04 10:45:31,baania,https://baania.com/th/project/บ้านแสนสบาย-1-pr...
4,1.0,1.0,2019-09-05 11:49:37,1970-01-02 07:00:00,2021-03-17 12:00:04,baania,https://baania.com/th/project/บ้านพฤกษา-ราชพฤก...

In [27]:
project_df.head().iloc[:5,-7:].dropna(thresh = 5)

,facility_pool,facility_security,date_created,date_finish,date_updated,source,url_project
0,1.0,1.0,2020-06-10 14:36:04,NaN,2020-12-04 10:32:58,baania,https://baania.com/th/project/วินนิ่ง-เรสซิเดน...
1,1.0,1.0,2017-10-30 15:38:48,2013-01-01 07:00:00,2020-12-04 10:49:00,baania,https://baania.com/th/project/กิ๊ฟท์-คอนโดมิเน...
3,NaN,NaN,2016-09-05 15:32:15,1970-01-02 07:00:00,2020-12-04 10:45:31,baania,https://baania.com/th/project/บ้านแสนสบาย-1-pr...
4,1.0,1.0,2019-09-05 11:49:37,1970-01-02 07:00:00,2021-03-17 12:00:04,baania,https://baania.com/th/project/บ้านพฤกษา-ราชพฤก...

In [30]:
project_df.dropna(subset = ['facility_pool'])

,row_number,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,price_min,developer_id,developer_name_en,...,facility_meeting,facility_park,facility_playground,facility_pool,facility_security,date_created,date_finish,date_updated,source,url_project
0,7880.0,5ee08d64dda791001299b2a6,Winning Residence Sukhumvit Praksa,วินนิ่ง เรสซิเดนท์ สุขุมวิท แพรกษา,1,Detached House,บ้าน,3790000.0,developer_10678,"Winning Asset Plus Co., Ltd.",...,NaN,NaN,NaN,1.0,1.0,2020-06-10 14:36:04,NaN,2020-12-04 10:32:58,baania,https://baania.com/th/project/วินนิ่ง-เรสซิเดน...
1,16689.0,project_11326,Gift Condominium,กิ๊ฟท์ คอนโดมิเนียม,2,Condo,คอนโด,1100000.0,developer_7319,"Gift Asset Land Co.,Ltd.",...,NaN,1.0,NaN,1.0,1.0,2017-10-30 15:38:48,2013-01-01 07:00:00,2020-12-04 10:49:00,baania,https://baania.com/th/project/กิ๊ฟท์-คอนโดมิเน...
4,199.0,project_16838,Baanpruksa Ratchapruek-345,บ้านพฤกษา ราชพฤกษ์-345,3,Townhome,ทาวน์โฮม,1930000.0,developer_1026,"Preuksa Real Estate Co.,Ltd.",...,NaN,1.0,NaN,1.0,1.0,2019-09-05 11:49:37,1970-01-02 07:00:00,2021-03-17 12:00:04,baania,https://baania.com/th/project/บ้านพฤกษา-ราชพฤก...
5,9434.0,project_15884,H2 Wood,เอชทู วูด,2,Condo,คอนโด,1480000.0,developer_1789,"Asset Wise Pub Co., Ltd.",...,0.0,0.0,0.0,1.0,1.0,2019-06-28 13:47:37,2015-12-31 07:00:00,2020-12-04 10:43:13,baania,https://baania.com/th/project/เอชทู-วูด-projec...
7,9022.0,project_1488,Homeland 3 Paradise Garden,โฮมแลนด์ 3 พาราไดซ์ การ์เด้น,1,Detached House,บ้าน,2600000.0,developer_1336,NaN,...,NaN,1.0,1.0,1.0,1.0,2016-06-10 14:52:22,2022-01-01 07:00:00,2022-02-28 18:30:07,baania,https://baania.com/th/project/โฮมแลนด์-3-พาราไ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23421,14537.0,project_10988,The Elegance @ Cosy Beach,ดิ เอเลแกนซ์ แอท โคซี บีช,2,Condo,คอนโด,2700000.0,developer_7118,"AML Development Co., Ltd.",...,0.0,1.0,0.0,1.0,1.0,2017-10-19 14:52:43,2017-12-31 07:00:00,2020-12-04 10:31:32,baania,https://baania.com/th/project/ดิ-เอเลแกนซ์-แอท...
23422,15130.0,project_17150,Baan Puttaraksa Saiwutphaderm-Ban Thung Bia,บ้านพุทธรักษา สายวัดประเดิม-บ้านทุ่งเบี้ย,4,Commercial,อาคารพาณิชย์,2490000.0,developer_2332,Apasiri Group,...,0.0,0.0,0.0,0.0,1.0,2020-01-16 13:09:08,2014-12-31 07:00:00,2020-12-04 10:34:57,baania,https://baania.com/th/project/บ้านพุทธรักษา-สา...
23425,19326.0,project_7618,The Base Chaengwattana,เดอะเบส แจ้งวัฒนะ,2,Condo,คอนโด,1148000.0,developer_36,"SANSIRI PUB CO., LTD.",...,NaN,1.0,NaN,1.0,1.0,2017-06-01 14:07:22,2013-12-31 07:00:00,2020-12-04 10:40:54,baania,https://baania.com/th/project/เดอะเบส-แจ้งวัฒน...
23426,6902.0,project_14944,Perfect residence krungthep-kreetha,เพอร์เฟค เรสซิเดนซ์ พระราม9-กรุงเทพกรีฑา,1,Detached House,บ้าน,10900000.0,developer_1751,"PROPERTY PERFECT PUB CO., LTD.",...,NaN,1.0,NaN,1.0,1.0,2018-10-31 15:41:58,1970-01-02 07:00:00,2021-06-28 16:00:09,baania,https://baania.com/th/project/เพอร์เฟค-เรสซิเด...
23432,5889.0,project_144,Koolpunt Ville 15 Park Avenue,กุลพันธ์วิลล์ 15 พาร์ค อเวนิว,1,Detached House,บ้าน,4000000.0,developer_1004,"Homeland Service Co., Ltd.",...,NaN,1.0,1.0,1.0,1.0,2015-09-28 09:00:28,2020-01-01 07:00:00,2022-01-10 15:00:13,baania,https://baania.com/th/project/กุลพันธ์วิลล์-15...

In [32]:
project_df.dropna(subset = [1,2], axis = 1)

,row_number,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,price_min,developer_id,latitude,...,district_name_en,district_name_th,province_id,province_name_en,province_name_th,zipcode,date_created,date_updated,source,url_project
0,7880.0,5ee08d64dda791001299b2a6,Winning Residence Sukhumvit Praksa,วินนิ่ง เรสซิเดนท์ สุขุมวิท แพรกษา,1,Detached House,บ้าน,3790000.0,developer_10678,13.570530,...,MUEANG SAMUT PRAKAN,เมืองสมุทรปราการ,3498.0,Samut Prakan,สมุทรปราการ,10280.0,2020-06-10 14:36:04,2020-12-04 10:32:58,baania,https://baania.com/th/project/วินนิ่ง-เรสซิเดน...
1,16689.0,project_11326,Gift Condominium,กิ๊ฟท์ คอนโดมิเนียม,2,Condo,คอนโด,1100000.0,developer_7319,13.033814,...,SI RACHA,ศรีราชา,4616.0,Chon Buri,ชลบุรี,20230.0,2017-10-30 15:38:48,2020-12-04 10:49:00,baania,https://baania.com/th/project/กิ๊ฟท์-คอนโดมิเน...
2,290.0,62739c4089233e001362b001,Sanrak 9 Sukprayoon Nong Krathum,แสนรัก 9 ศุขประยูร หนองกระทุ่ม,3,Townhome,ทาวน์โฮม,0.0,developer_10510,13.417402,...,PHAN THONG,พานทอง,4616.0,Chon Buri,ชลบุรี,20160.0,2022-05-05 16:43:28,2022-05-05 17:30:03,baania,https://baania.com/th/project/แสนรัก-9-ศุขประย...
3,20719.0,project_2010,Baan Sansabai 1,บ้านแสนสบาย 1,1,Detached House,บ้าน,0.0,developer_10510,15.038042,...,MUEANG NAKHON RATCHASIMA,เมืองนครราชสีมา,2857.0,Nakhon Ratchasima,นครราชสีมา,30000.0,2016-09-05 15:32:15,2020-12-04 10:45:31,baania,https://baania.com/th/project/บ้านแสนสบาย-1-pr...
4,199.0,project_16838,Baanpruksa Ratchapruek-345,บ้านพฤกษา ราชพฤกษ์-345,3,Townhome,ทาวน์โฮม,1930000.0,developer_1026,13.965246,...,MUEANG PATHUM THANI,เมืองปทุมธานี,3599.0,Pathum Thani,ปทุมธานี,12000.0,2019-09-05 11:49:37,2021-03-17 12:00:04,baania,https://baania.com/th/project/บ้านพฤกษา-ราชพฤก...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23429,12883.0,project_12317,Baan Klangmeung Urbanion Ladphrao-Chokchai 4,บ้านกลางเมือง เออร์บาเนี่ยน ลาดพร้าว-โชคชัย 4,3,Townhome,ทาวน์โฮม,5700000.0,developer_1760,13.814468,...,LAT PHRAO,ลาดพร้าว,3781.0,Bangkok,กรุงเทพมหานคร,10230.0,2017-12-06 13:10:23,2020-12-04 10:42:15,baania,https://baania.com/th/project/บ้านกลางเมือง-เอ...
23430,21181.0,project_12057,@Home Kaset-Nawamin,แอทโฮม เกษตร-นวมินทร์,3,Townhome,ทาวน์โฮม,3590000.0,developer_1793,13.834361,...,LAT PHRAO,ลาดพร้าว,3781.0,Bangkok,กรุงเทพมหานคร,10230.0,2017-11-30 11:12:12,2022-06-06 16:30:06,baania,https://baania.com/th/project/แอทโฮม-เกษตร-นวม...
23431,13993.0,project_4461,I-Design Wongwaen-Ramintra,ไอ-ดีไซน์ วงแหวน-รามอินทรา,4,Commercial,อาคารพาณิชย์,1870000.0,developer_2217,13.859872,...,KHLONG SAM WA,คลองสามวา,3781.0,Bangkok,กรุงเทพมหานคร,10510.0,2017-03-02 11:07:30,2020-12-04 10:42:33,baania,https://baania.com/th/project/ไอ-ดีไซน์-วงแหวน...
23432,5889.0,project_144,Koolpunt Ville 15 Park Avenue,กุลพันธ์วิลล์ 15 พาร์ค อเวนิว,1,Detached House,บ้าน,4000000.0,developer_1004,18.808447,...,DOI SAKET,ดอยสะเก็ด,1005.0,Chiang Mai,เชียงใหม่,50220.0,2015-09-28 09:00:28,2022-01-10 15:00:13,baania,https://baania.com/th/project/กุลพันธ์วิลล์-15...
23433,5529.0,project_16300,Thawisuk Garden Home,ทวีสุข การ์เด้นโฮม,1,Detached House,บ้าน,2800000.0,developer_10510,12.684945,...,BAN CHANG,บ้านฉาง,3431.0,Rayong,ระยอง,21330.0,2019-07-05 17:10:33,2020-12-04 10:45:22,baania,https://baania.com/th/project/ทวีสุข-การ์เด้นโ...

In [33]:
project_df.dropna(subset = ['propertytype_name_en','price_min'])

,row_number,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,price_min,developer_id,developer_name_en,...,facility_meeting,facility_park,facility_playground,facility_pool,facility_security,date_created,date_finish,date_updated,source,url_project
0,7880.0,5ee08d64dda791001299b2a6,Winning Residence Sukhumvit Praksa,วินนิ่ง เรสซิเดนท์ สุขุมวิท แพรกษา,1,Detached House,บ้าน,3790000.0,developer_10678,"Winning Asset Plus Co., Ltd.",...,NaN,NaN,NaN,1.0,1.0,2020-06-10 14:36:04,NaN,2020-12-04 10:32:58,baania,https://baania.com/th/project/วินนิ่ง-เรสซิเดน...
1,16689.0,project_11326,Gift Condominium,กิ๊ฟท์ คอนโดมิเนียม,2,Condo,คอนโด,1100000.0,developer_7319,"Gift Asset Land Co.,Ltd.",...,NaN,1.0,NaN,1.0,1.0,2017-10-30 15:38:48,2013-01-01 07:00:00,2020-12-04 10:49:00,baania,https://baania.com/th/project/กิ๊ฟท์-คอนโดมิเน...
2,290.0,62739c4089233e001362b001,Sanrak 9 Sukprayoon Nong Krathum,แสนรัก 9 ศุขประยูร หนองกระทุ่ม,3,Townhome,ทาวน์โฮม,0.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,NaN,2022-05-05 16:43:28,NaN,2022-05-05 17:30:03,baania,https://baania.com/th/project/แสนรัก-9-ศุขประย...
3,20719.0,project_2010,Baan Sansabai 1,บ้านแสนสบาย 1,1,Detached House,บ้าน,0.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,NaN,2016-09-05 15:32:15,1970-01-02 07:00:00,2020-12-04 10:45:31,baania,https://baania.com/th/project/บ้านแสนสบาย-1-pr...
4,199.0,project_16838,Baanpruksa Ratchapruek-345,บ้านพฤกษา ราชพฤกษ์-345,3,Townhome,ทาวน์โฮม,1930000.0,developer_1026,"Preuksa Real Estate Co.,Ltd.",...,NaN,1.0,NaN,1.0,1.0,2019-09-05 11:49:37,1970-01-02 07:00:00,2021-03-17 12:00:04,baania,https://baania.com/th/project/บ้านพฤกษา-ราชพฤก...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23429,12883.0,project_12317,Baan Klangmeung Urbanion Ladphrao-Chokchai 4,บ้านกลางเมือง เออร์บาเนี่ยน ลาดพร้าว-โชคชัย 4,3,Townhome,ทาวน์โฮม,5700000.0,developer_1760,"AP (Thailand) Co,. Ltd",...,NaN,1.0,1.0,NaN,1.0,2017-12-06 13:10:23,1970-01-02 07:00:00,2020-12-04 10:42:15,baania,https://baania.com/th/project/บ้านกลางเมือง-เอ...
23430,21181.0,project_12057,@Home Kaset-Nawamin,แอทโฮม เกษตร-นวมินทร์,3,Townhome,ทาวน์โฮม,3590000.0,developer_1793,"Areeya Property Co.,Ltd.",...,NaN,NaN,NaN,NaN,1.0,2017-11-30 11:12:12,1970-01-02 07:00:00,2022-06-06 16:30:06,baania,https://baania.com/th/project/แอทโฮม-เกษตร-นวม...
23431,13993.0,project_4461,I-Design Wongwaen-Ramintra,ไอ-ดีไซน์ วงแหวน-รามอินทรา,4,Commercial,อาคารพาณิชย์,1870000.0,developer_2217,"Wangthong Group Pub Co., Ltd.",...,NaN,1.0,1.0,NaN,1.0,2017-03-02 11:07:30,2014-12-31 07:00:00,2020-12-04 10:42:33,baania,https://baania.com/th/project/ไอ-ดีไซน์-วงแหวน...
23432,5889.0,project_144,Koolpunt Ville 15 Park Avenue,กุลพันธ์วิลล์ 15 พาร์ค อเวนิว,1,Detached House,บ้าน,4000000.0,developer_1004,"Homeland Service Co., Ltd.",...,NaN,1.0,1.0,1.0,1.0,2015-09-28 09:00:28,2020-01-01 07:00:00,2022-01-10 15:00:13,baania,https://baania.com/th/project/กุลพันธ์วิลล์-15...
23433,5529.0,project_16300,Thawisuk Garden Home,ทวีสุข การ์เด้นโฮม,1,Detached House,บ้าน,2800000.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,NaN,2019-07-05 17:10:33,1970-01-02 07:00:00,2020-12-04 10:45:22,baania,https://baania.com/th/project/ทวีสุข-การ์เด้นโ...

In [35]:
project_df.dropna(subset = ['propertytype_name_en','price_min']).isnull().any()

row_number                 True
project_id                False
name_en                   False
name_th                   False
propertytype_id           False
propertytype_name_en      False
propertytype_name_th      False
price_min                 False
developer_id              False
developer_name_en          True
developer_name_th          True
latitude                  False
longitude                  True
neighborhood_id            True
neighborhood_name_en       True
neighborhood_name_th       True
subdistrict_id             True
subdistrict_name_en        True
subdistrict_name_th        True
district_id                True
district_name_en           True
district_name_th           True
province_id                True
province_name_en           True
province_name_th           True
zipcode                    True
count_elevator             True
count_elevator_service     True
count_floor                True
count_parking              True
count_tower                True
count_unit                 True
count_unittype             True
facility_clubhouse         True
facility_fitness           True
facility_meeting           True
facility_park              True
facility_playground        True
facility_pool              True
facility_security          True
date_created               True
date_finish                True
date_updated               True
source                     True
url_project                True
dtype: bool

In [37]:
project_df.dropna(subset = ['propertytype_name_en','price_min'] ,inplace =True)

1. กำจัดค่า missing โดยการตัด column ให้น้อยที่สุด โดยที่จำนวน records ที่ไม่มี missing เลย ยังเหลือมากกว่า 80% 

2. สร้าง DATA ที่ ค่าใน columns [price_min, neighborhood_name_en,developer_name_en] มี missing ไม่เกิน 1 ค่า

In [38]:
project_df = pd.read_csv('/content/drive/MyDrive/DPDM65/Copy of opendata_project.csv')
project_df.head()

,row_number,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,price_min,developer_id,developer_name_en,...,facility_meeting,facility_park,facility_playground,facility_pool,facility_security,date_created,date_finish,date_updated,source,url_project
0,7880.0,5ee08d64dda791001299b2a6,Winning Residence Sukhumvit Praksa,วินนิ่ง เรสซิเดนท์ สุขุมวิท แพรกษา,1,Detached House,บ้าน,3790000.0,developer_10678,"Winning Asset Plus Co., Ltd.",...,NaN,NaN,NaN,1.0,1.0,2020-06-10 14:36:04,NaN,2020-12-04 10:32:58,baania,https://baania.com/th/project/วินนิ่ง-เรสซิเดน...
1,16689.0,project_11326,Gift Condominium,กิ๊ฟท์ คอนโดมิเนียม,2,Condo,คอนโด,1100000.0,developer_7319,"Gift Asset Land Co.,Ltd.",...,NaN,1.0,NaN,1.0,1.0,2017-10-30 15:38:48,2013-01-01 07:00:00,2020-12-04 10:49:00,baania,https://baania.com/th/project/กิ๊ฟท์-คอนโดมิเน...
2,290.0,62739c4089233e001362b001,Sanrak 9 Sukprayoon Nong Krathum,แสนรัก 9 ศุขประยูร หนองกระทุ่ม,3,Townhome,ทาวน์โฮม,0.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,NaN,2022-05-05 16:43:28,NaN,2022-05-05 17:30:03,baania,https://baania.com/th/project/แสนรัก-9-ศุขประย...
3,20719.0,project_2010,Baan Sansabai 1,บ้านแสนสบาย 1,1,Detached House,บ้าน,0.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,NaN,2016-09-05 15:32:15,1970-01-02 07:00:00,2020-12-04 10:45:31,baania,https://baania.com/th/project/บ้านแสนสบาย-1-pr...
4,199.0,project_16838,Baanpruksa Ratchapruek-345,บ้านพฤกษา ราชพฤกษ์-345,3,Townhome,ทาวน์โฮม,1930000.0,developer_1026,"Preuksa Real Estate Co.,Ltd.",...,NaN,1.0,NaN,1.0,1.0,2019-09-05 11:49:37,1970-01-02 07:00:00,2021-03-17 12:00:04,baania,https://baania.com/th/project/บ้านพฤกษา-ราชพฤก...

1. กำจัดค่า missing โดยการตัด column ให้น้อยที่สุด โดยที่จำนวน records ที่ไม่มี missing เลย ยังเหลือมากกว่า 80%

In [56]:
project_df.dropna(thresh = 23434*80/100,axis = 1)

,row_number,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,price_min,developer_id,latitude,...,province_id,province_name_en,province_name_th,zipcode,count_unit,date_created,date_finish,date_updated,source,url_project
0,7880.0,5ee08d64dda791001299b2a6,Winning Residence Sukhumvit Praksa,วินนิ่ง เรสซิเดนท์ สุขุมวิท แพรกษา,1,Detached House,บ้าน,3790000.0,developer_10678,13.570530,...,3498.0,Samut Prakan,สมุทรปราการ,10280.0,NaN,2020-06-10 14:36:04,NaN,2020-12-04 10:32:58,baania,https://baania.com/th/project/วินนิ่ง-เรสซิเดน...
1,16689.0,project_11326,Gift Condominium,กิ๊ฟท์ คอนโดมิเนียม,2,Condo,คอนโด,1100000.0,developer_7319,13.033814,...,4616.0,Chon Buri,ชลบุรี,20230.0,77.0,2017-10-30 15:38:48,2013-01-01 07:00:00,2020-12-04 10:49:00,baania,https://baania.com/th/project/กิ๊ฟท์-คอนโดมิเน...
2,290.0,62739c4089233e001362b001,Sanrak 9 Sukprayoon Nong Krathum,แสนรัก 9 ศุขประยูร หนองกระทุ่ม,3,Townhome,ทาวน์โฮม,0.0,developer_10510,13.417402,...,4616.0,Chon Buri,ชลบุรี,20160.0,NaN,2022-05-05 16:43:28,NaN,2022-05-05 17:30:03,baania,https://baania.com/th/project/แสนรัก-9-ศุขประย...
3,20719.0,project_2010,Baan Sansabai 1,บ้านแสนสบาย 1,1,Detached House,บ้าน,0.0,developer_10510,15.038042,...,2857.0,Nakhon Ratchasima,นครราชสีมา,30000.0,NaN,2016-09-05 15:32:15,1970-01-02 07:00:00,2020-12-04 10:45:31,baania,https://baania.com/th/project/บ้านแสนสบาย-1-pr...
4,199.0,project_16838,Baanpruksa Ratchapruek-345,บ้านพฤกษา ราชพฤกษ์-345,3,Townhome,ทาวน์โฮม,1930000.0,developer_1026,13.965246,...,3599.0,Pathum Thani,ปทุมธานี,12000.0,485.0,2019-09-05 11:49:37,1970-01-02 07:00:00,2021-03-17 12:00:04,baania,https://baania.com/th/project/บ้านพฤกษา-ราชพฤก...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23429,12883.0,project_12317,Baan Klangmeung Urbanion Ladphrao-Chokchai 4,บ้านกลางเมือง เออร์บาเนี่ยน ลาดพร้าว-โชคชัย 4,3,Townhome,ทาวน์โฮม,5700000.0,developer_1760,13.814468,...,3781.0,Bangkok,กรุงเทพมหานคร,10230.0,123.0,2017-12-06 13:10:23,1970-01-02 07:00:00,2020-12-04 10:42:15,baania,https://baania.com/th/project/บ้านกลางเมือง-เอ...
23430,21181.0,project_12057,@Home Kaset-Nawamin,แอทโฮม เกษตร-นวมินทร์,3,Townhome,ทาวน์โฮม,3590000.0,developer_1793,13.834361,...,3781.0,Bangkok,กรุงเทพมหานคร,10230.0,55.0,2017-11-30 11:12:12,1970-01-02 07:00:00,2022-06-06 16:30:06,baania,https://baania.com/th/project/แอทโฮม-เกษตร-นวม...
23431,13993.0,project_4461,I-Design Wongwaen-Ramintra,ไอ-ดีไซน์ วงแหวน-รามอินทรา,4,Commercial,อาคารพาณิชย์,1870000.0,developer_2217,13.859872,...,3781.0,Bangkok,กรุงเทพมหานคร,10510.0,292.0,2017-03-02 11:07:30,2014-12-31 07:00:00,2020-12-04 10:42:33,baania,https://baania.com/th/project/ไอ-ดีไซน์-วงแหวน...
23432,5889.0,project_144,Koolpunt Ville 15 Park Avenue,กุลพันธ์วิลล์ 15 พาร์ค อเวนิว,1,Detached House,บ้าน,4000000.0,developer_1004,18.808447,...,1005.0,Chiang Mai,เชียงใหม่,50220.0,259.0,2015-09-28 09:00:28,2020-01-01 07:00:00,2022-01-10 15:00:13,baania,https://baania.com/th/project/กุลพันธ์วิลล์-15...
23433,5529.0,project_16300,Thawisuk Garden Home,ทวีสุข การ์เด้นโฮม,1,Detached House,บ้าน,2800000.0,developer_10510,12.684945,...,3431.0,Rayong,ระยอง,21330.0,70.0,2019-07-05 17:10:33,1970-01-02 07:00:00,2020-12-04 10:45:22,baania,https://baania.com/th/project/ทวีสุข-การ์เด้นโ...

In [58]:
project_df.dropna(thresh = 23434*80/100,axis = 1).dropna()

,row_number,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,price_min,developer_id,latitude,...,province_id,province_name_en,province_name_th,zipcode,count_unit,date_created,date_finish,date_updated,source,url_project
1,16689.0,project_11326,Gift Condominium,กิ๊ฟท์ คอนโดมิเนียม,2,Condo,คอนโด,1100000.0,developer_7319,13.033814,...,4616.0,Chon Buri,ชลบุรี,20230.0,77.0,2017-10-30 15:38:48,2013-01-01 07:00:00,2020-12-04 10:49:00,baania,https://baania.com/th/project/กิ๊ฟท์-คอนโดมิเน...
4,199.0,project_16838,Baanpruksa Ratchapruek-345,บ้านพฤกษา ราชพฤกษ์-345,3,Townhome,ทาวน์โฮม,1930000.0,developer_1026,13.965246,...,3599.0,Pathum Thani,ปทุมธานี,12000.0,485.0,2019-09-05 11:49:37,1970-01-02 07:00:00,2021-03-17 12:00:04,baania,https://baania.com/th/project/บ้านพฤกษา-ราชพฤก...
5,9434.0,project_15884,H2 Wood,เอชทู วูด,2,Condo,คอนโด,1480000.0,developer_1789,13.865311,...,3781.0,Bangkok,กรุงเทพมหานคร,10220.0,79.0,2019-06-28 13:47:37,2015-12-31 07:00:00,2020-12-04 10:43:13,baania,https://baania.com/th/project/เอชทู-วูด-projec...
7,9022.0,project_1488,Homeland 3 Paradise Garden,โฮมแลนด์ 3 พาราไดซ์ การ์เด้น,1,Detached House,บ้าน,2600000.0,developer_1336,14.973075,...,2857.0,Nakhon Ratchasima,นครราชสีมา,30000.0,309.0,2016-06-10 14:52:22,2022-01-01 07:00:00,2022-02-28 18:30:07,baania,https://baania.com/th/project/โฮมแลนด์-3-พาราไ...
8,7266.0,project_6637,Lumpini Place Rama 4-Sathorn,ลุมพินีเพลสพระราม 4-สาทร,2,Condo,คอนโด,1990000.0,developer_1745,13.718633,...,3781.0,Bangkok,กรุงเทพมหานคร,10120.0,231.0,2017-05-04 13:45:47,2003-12-31 07:00:00,2020-12-04 10:40:46,baania,https://baania.com/th/project/ลุมพินีเพลสพระรา...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23429,12883.0,project_12317,Baan Klangmeung Urbanion Ladphrao-Chokchai 4,บ้านกลางเมือง เออร์บาเนี่ยน ลาดพร้าว-โชคชัย 4,3,Townhome,ทาวน์โฮม,5700000.0,developer_1760,13.814468,...,3781.0,Bangkok,กรุงเทพมหานคร,10230.0,123.0,2017-12-06 13:10:23,1970-01-02 07:00:00,2020-12-04 10:42:15,baania,https://baania.com/th/project/บ้านกลางเมือง-เอ...
23430,21181.0,project_12057,@Home Kaset-Nawamin,แอทโฮม เกษตร-นวมินทร์,3,Townhome,ทาวน์โฮม,3590000.0,developer_1793,13.834361,...,3781.0,Bangkok,กรุงเทพมหานคร,10230.0,55.0,2017-11-30 11:12:12,1970-01-02 07:00:00,2022-06-06 16:30:06,baania,https://baania.com/th/project/แอทโฮม-เกษตร-นวม...
23431,13993.0,project_4461,I-Design Wongwaen-Ramintra,ไอ-ดีไซน์ วงแหวน-รามอินทรา,4,Commercial,อาคารพาณิชย์,1870000.0,developer_2217,13.859872,...,3781.0,Bangkok,กรุงเทพมหานคร,10510.0,292.0,2017-03-02 11:07:30,2014-12-31 07:00:00,2020-12-04 10:42:33,baania,https://baania.com/th/project/ไอ-ดีไซน์-วงแหวน...
23432,5889.0,project_144,Koolpunt Ville 15 Park Avenue,กุลพันธ์วิลล์ 15 พาร์ค อเวนิว,1,Detached House,บ้าน,4000000.0,developer_1004,18.808447,...,1005.0,Chiang Mai,เชียงใหม่,50220.0,259.0,2015-09-28 09:00:28,2020-01-01 07:00:00,2022-01-10 15:00:13,baania,https://baania.com/th/project/กุลพันธ์วิลล์-15...
23433,5529.0,project_16300,Thawisuk Garden Home,ทวีสุข การ์เด้นโฮม,1,Detached House,บ้าน,2800000.0,developer_10510,12.684945,...,3431.0,Rayong,ระยอง,21330.0,70.0,2019-07-05 17:10:33,1970-01-02 07:00:00,2020-12-04 10:45:22,baania,https://baania.com/th/project/ทวีสุข-การ์เด้นโ...

2. สร้าง DATA ที่ ค่าใน columns [price_min, neighborhood_name_en,developer_name_en] มี missing ไม่เกิน 1 ค่า

In [61]:
project_df.dropna(subset = ['price_min', 'neighborhood_name_en','developer_name_en'],thresh =2)

,row_number,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,price_min,developer_id,developer_name_en,...,facility_meeting,facility_park,facility_playground,facility_pool,facility_security,date_created,date_finish,date_updated,source,url_project
0,7880.0,5ee08d64dda791001299b2a6,Winning Residence Sukhumvit Praksa,วินนิ่ง เรสซิเดนท์ สุขุมวิท แพรกษา,1,Detached House,บ้าน,3790000.0,developer_10678,"Winning Asset Plus Co., Ltd.",...,NaN,NaN,NaN,1.0,1.0,2020-06-10 14:36:04,NaN,2020-12-04 10:32:58,baania,https://baania.com/th/project/วินนิ่ง-เรสซิเดน...
1,16689.0,project_11326,Gift Condominium,กิ๊ฟท์ คอนโดมิเนียม,2,Condo,คอนโด,1100000.0,developer_7319,"Gift Asset Land Co.,Ltd.",...,NaN,1.0,NaN,1.0,1.0,2017-10-30 15:38:48,2013-01-01 07:00:00,2020-12-04 10:49:00,baania,https://baania.com/th/project/กิ๊ฟท์-คอนโดมิเน...
2,290.0,62739c4089233e001362b001,Sanrak 9 Sukprayoon Nong Krathum,แสนรัก 9 ศุขประยูร หนองกระทุ่ม,3,Townhome,ทาวน์โฮม,0.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,NaN,2022-05-05 16:43:28,NaN,2022-05-05 17:30:03,baania,https://baania.com/th/project/แสนรัก-9-ศุขประย...
3,20719.0,project_2010,Baan Sansabai 1,บ้านแสนสบาย 1,1,Detached House,บ้าน,0.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,NaN,2016-09-05 15:32:15,1970-01-02 07:00:00,2020-12-04 10:45:31,baania,https://baania.com/th/project/บ้านแสนสบาย-1-pr...
4,199.0,project_16838,Baanpruksa Ratchapruek-345,บ้านพฤกษา ราชพฤกษ์-345,3,Townhome,ทาวน์โฮม,1930000.0,developer_1026,"Preuksa Real Estate Co.,Ltd.",...,NaN,1.0,NaN,1.0,1.0,2019-09-05 11:49:37,1970-01-02 07:00:00,2021-03-17 12:00:04,baania,https://baania.com/th/project/บ้านพฤกษา-ราชพฤก...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23429,12883.0,project_12317,Baan Klangmeung Urbanion Ladphrao-Chokchai 4,บ้านกลางเมือง เออร์บาเนี่ยน ลาดพร้าว-โชคชัย 4,3,Townhome,ทาวน์โฮม,5700000.0,developer_1760,"AP (Thailand) Co,. Ltd",...,NaN,1.0,1.0,NaN,1.0,2017-12-06 13:10:23,1970-01-02 07:00:00,2020-12-04 10:42:15,baania,https://baania.com/th/project/บ้านกลางเมือง-เอ...
23430,21181.0,project_12057,@Home Kaset-Nawamin,แอทโฮม เกษตร-นวมินทร์,3,Townhome,ทาวน์โฮม,3590000.0,developer_1793,"Areeya Property Co.,Ltd.",...,NaN,NaN,NaN,NaN,1.0,2017-11-30 11:12:12,1970-01-02 07:00:00,2022-06-06 16:30:06,baania,https://baania.com/th/project/แอทโฮม-เกษตร-นวม...
23431,13993.0,project_4461,I-Design Wongwaen-Ramintra,ไอ-ดีไซน์ วงแหวน-รามอินทรา,4,Commercial,อาคารพาณิชย์,1870000.0,developer_2217,"Wangthong Group Pub Co., Ltd.",...,NaN,1.0,1.0,NaN,1.0,2017-03-02 11:07:30,2014-12-31 07:00:00,2020-12-04 10:42:33,baania,https://baania.com/th/project/ไอ-ดีไซน์-วงแหวน...
23432,5889.0,project_144,Koolpunt Ville 15 Park Avenue,กุลพันธ์วิลล์ 15 พาร์ค อเวนิว,1,Detached House,บ้าน,4000000.0,developer_1004,"Homeland Service Co., Ltd.",...,NaN,1.0,1.0,1.0,1.0,2015-09-28 09:00:28,2020-01-01 07:00:00,2022-01-10 15:00:13,baania,https://baania.com/th/project/กุลพันธ์วิลล์-15...
23433,5529.0,project_16300,Thawisuk Garden Home,ทวีสุข การ์เด้นโฮม,1,Detached House,บ้าน,2800000.0,developer_10510,NaN,...,NaN,NaN,NaN,NaN,NaN,2019-07-05 17:10:33,1970-01-02 07:00:00,2020-12-04 10:45:22,baania,https://baania.com/th/project/ทวีสุข-การ์เด้นโ...

In [54]:
project_df.dropna(subset = ['price_min', 'neighborhood_name_en','developer_name_en'])

,row_number,project_id,name_en,name_th,propertytype_id,propertytype_name_en,propertytype_name_th,price_min,developer_id,developer_name_en,...,facility_meeting,facility_park,facility_playground,facility_pool,facility_security,date_created,date_finish,date_updated,source,url_project
0,7880.0,5ee08d64dda791001299b2a6,Winning Residence Sukhumvit Praksa,วินนิ่ง เรสซิเดนท์ สุขุมวิท แพรกษา,1,Detached House,บ้าน,3790000.0,developer_10678,"Winning Asset Plus Co., Ltd.",...,NaN,NaN,NaN,1.0,1.0,2020-06-10 14:36:04,NaN,2020-12-04 10:32:58,baania,https://baania.com/th/project/วินนิ่ง-เรสซิเดน...
1,16689.0,project_11326,Gift Condominium,กิ๊ฟท์ คอนโดมิเนียม,2,Condo,คอนโด,1100000.0,developer_7319,"Gift Asset Land Co.,Ltd.",...,NaN,1.0,NaN,1.0,1.0,2017-10-30 15:38:48,2013-01-01 07:00:00,2020-12-04 10:49:00,baania,https://baania.com/th/project/กิ๊ฟท์-คอนโดมิเน...
4,199.0,project_16838,Baanpruksa Ratchapruek-345,บ้านพฤกษา ราชพฤกษ์-345,3,Townhome,ทาวน์โฮม,1930000.0,developer_1026,"Preuksa Real Estate Co.,Ltd.",...,NaN,1.0,NaN,1.0,1.0,2019-09-05 11:49:37,1970-01-02 07:00:00,2021-03-17 12:00:04,baania,https://baania.com/th/project/บ้านพฤกษา-ราชพฤก...
5,9434.0,project_15884,H2 Wood,เอชทู วูด,2,Condo,คอนโด,1480000.0,developer_1789,"Asset Wise Pub Co., Ltd.",...,0.0,0.0,0.0,1.0,1.0,2019-06-28 13:47:37,2015-12-31 07:00:00,2020-12-04 10:43:13,baania,https://baania.com/th/project/เอชทู-วูด-projec...
8,7266.0,project_6637,Lumpini Place Rama 4-Sathorn,ลุมพินีเพลสพระราม 4-สาทร,2,Condo,คอนโด,1990000.0,developer_1745,"L.P.N.Development PCL Co., Ltd.",...,NaN,NaN,1.0,1.0,1.0,2017-05-04 13:45:47,2003-12-31 07:00:00,2020-12-04 10:40:46,baania,https://baania.com/th/project/ลุมพินีเพลสพระรา...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23428,8894.0,project_12905,J Business Center,เจ บิสซิเนส เซ็นเตอร์,4,Commercial,อาคารพาณิชย์,7299000.0,developer_5736,"Ornsirin Property Co.,Ltd.",...,NaN,NaN,NaN,NaN,NaN,2018-01-22 10:07:46,2014-06-30 07:00:00,2021-04-05 11:00:04,baania,https://baania.com/th/project/เจ-บิสซิเนส-เซ็น...
23429,12883.0,project_12317,Baan Klangmeung Urbanion Ladphrao-Chokchai 4,บ้านกลางเมือง เออร์บาเนี่ยน ลาดพร้าว-โชคชัย 4,3,Townhome,ทาวน์โฮม,5700000.0,developer_1760,"AP (Thailand) Co,. Ltd",...,NaN,1.0,1.0,NaN,1.0,2017-12-06 13:10:23,1970-01-02 07:00:00,2020-12-04 10:42:15,baania,https://baania.com/th/project/บ้านกลางเมือง-เอ...
23430,21181.0,project_12057,@Home Kaset-Nawamin,แอทโฮม เกษตร-นวมินทร์,3,Townhome,ทาวน์โฮม,3590000.0,developer_1793,"Areeya Property Co.,Ltd.",...,NaN,NaN,NaN,NaN,1.0,2017-11-30 11:12:12,1970-01-02 07:00:00,2022-06-06 16:30:06,baania,https://baania.com/th/project/แอทโฮม-เกษตร-นวม...
23431,13993.0,project_4461,I-Design Wongwaen-Ramintra,ไอ-ดีไซน์ วงแหวน-รามอินทรา,4,Commercial,อาคารพาณิชย์,1870000.0,developer_2217,"Wangthong Group Pub Co., Ltd.",...,NaN,1.0,1.0,NaN,1.0,2017-03-02 11:07:30,2014-12-31 07:00:00,2020-12-04 10:42:33,baania,https://baania.com/th/project/ไอ-ดีไซน์-วงแหวน...
23432,5889.0,project_144,Koolpunt Ville 15 Park Avenue,กุลพันธ์วิลล์ 15 พาร์ค อเวนิว,1,Detached House,บ้าน,4000000.0,developer_1004,"Homeland Service Co., Ltd.",...,NaN,1.0,1.0,1.0,1.0,2015-09-28 09:00:28,2020-01-01 07:00:00,2022-01-10 15:00:13,baania,https://baania.com/th/project/กุลพันธ์วิลล์-15...